<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
    <div class="card card-outline card-primary">
        <div class="card-header">
            <h3 class="card-title font-weight-bold">Lista de Cursos y Talleres Registrados</h3>
        </div>
        <div class="card-body">
            <table id="table-cursos-y-talleres" class="table table-striped table-sm table-hover"
                   data-pagination="true"
                   data-unique-id="id"
                   data-search="true"
                   data-locale="es-MX"
                   data-show-refresh="true"
                   data-url="<?= $this->url('coursesAndWorkshopsDashboardAccess/coursesAndWorkshops', ['action' => 'listOfCoursesAndWorkshops']) ?>"
                   data-show-columns="true">
                <thead>
                <tr>
                    <th data-field="estatus"><i class="fa fa-bookmark"></i></th>
                    <th data-field="id" data-visible="false">Id</th>
                    <th data-field="titulo" data-align="center" data-sortable="true">Titulo</th>
                    <th data-field="subtitulo" data-align="center" data-sortable="true">Subtitulo</th>
                    <th data-field="fechaInicio" data-align="center" data-sortable="true">Fecha de Inicio</th>
                    <th data-field="fechaTermino" data-align="center" data-sortable="true">Fecha de Termino</th>
                    <th data-field="catEstatusPublicacionId" data-align="center" data-sortable="true">Estatus de
                        publicación
                    </th>
                    <th data-field="preview" data-align="center"><i class="fa fa-cogs"></i></th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
    <script>
        let $table = $("table");
        $table.bootstrapTable();
    </script>
<?= $this->inlineScript()->appendFile($this->basePath('js/changeStatus.js')) ?>