<?php
/**
 * @var Laminas\View\Helper\Navigation $this
 */
?>
<?php

foreach ($this->container as $page) {

    $hasChildren = $page->hasPages();
    if (!$hasChildren) { ?>
        <li class="nav-item">
            <a href="<?= $page->getHref(); ?>" class="nav-link <?= $page->isActive() ? 'active' : '' ?>">
                <?php echo $page->getLabel(); ?>
            </a>
        </li>
    <?php } else { ?>
        <li class="nav-item has-treeview <?= $page->isActive() ? ' menu-open ' : '' ?>">
            <a href="#"
               class="nav-link <?= $page->isActive() ? ' active ' : '' ?>">
                <i class="nav-icon fas fa-circle"></i>
                <p>
                    <?php echo $page->getLabel(); ?>
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <?php foreach ($page->getPages() as $child) { ?>
                    <li class="nav-item <?= $child->hasPages() ? 'has-treeview' : '' ?> <?= $child->isActive() ? ' menu-open ' : '' ?>">
                        <a href="<?= $child->hasPages() ? '#' : $child->getHref() ?>"
                           class="nav-link <?= $child->isActive() ? ' active ' : '' ?>">
                            <i class="far fa-circle nav-icon"></i>
                            <p>
                                <?= $child->getLabel(); ?>
                                <?php if ($child->hasPages()) { ?>
                                    <i class="right fas fa-angle-left"></i>
                                <?php } ?>
                            </p>
                        </a>
                        <?php if ($child->hasPages()) { ?>
                            <ul class="nav nav-treeview">
                                <?php foreach ($child->getPages() as $subChild) { ?>
                                    <li class="nav-item">
                                        <a href="<?= $subChild->getHref() ?>"
                                           class="nav-link <?= $subChild->isActive() ? ' active-submenu ' : '' ?>">
                                            <i class="far fa-dot-circle nav-icon"></i>
                                            <p><?= $subChild->getLabel() ?></p>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
        </li>
    <?php }
} ?>
