<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
<div class="card">
    <div class="card-header bg-info pb-0">
        <ul class="nav nav-tabs border-bottom-0" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="practica-1-tab" data-toggle="tab" href="#practica-1" role="tab"
                   aria-controls="practica-1" aria-selected="true">Practica 1</a>
            </li>
            <!--            <li class="nav-item" role="presentation">-->
            <!--                <a class="nav-link" id="practica-2-tab" data-toggle="tab" href="#practica-2" role="tab"-->
            <!--                   aria-controls="practica-2" aria-selected="false">Practica 2</a>-->
            <!--            </li>-->
            <!--            <li class="nav-item" role="presentation">-->
            <!--                <a class="nav-link" id="practica-3-tab" data-toggle="tab" href="#practica-3" role="tab"-->
            <!--                   aria-controls="practica-3" aria-selected="false">Practica 3</a>-->
            <!--            </li>-->
        </ul>
    </div>
    <div class="card-body">
        <div class="tab-content">
            <div class="tab-pane fade show active" id="practica-1" role="tabpanel" aria-labelledby="practica-1-tab">
                <div class="row">
                    <div class="col">
                        <div class="callout callout-info">
                            <h4>Descripción de la actividad y pautas de elaboración</h4>
                            <p>Se debe diseñar y desarrollar una aplicación web funcional cumpliendo los criterios de
                                evaluación
                                expuestos a continuación.</p>
                        </div>
                        <div class="callout callout-info">
                            <h4>Criterios de evaluación</h4>
                            <p>La aplicación a desarrollar puede tener una temática libre (por ejemplo: un blog, una
                                página de
                                eventos, etc.) debe cumplir con los siguientes requisitos básicos:</p>
                            <ul>
                                <li>La aplicación a desarrollar puede tener una temática libre (por ejemplo: un blog,
                                    una página de
                                    eventos, etc.) debe cumplir con los siguientes requisitos básicos:
                                </li>
                                <li>Persistencia (2 puntos): se debe utilizar una base de datos MySQL o MongoDB (a
                                    elección del
                                    alumno) para almacenar al menos dos tipos de entidades distintas que dependerán de
                                    la temática
                                    de la aplicación (proyectos, tareas, partidos, jugadores, cuentas, etc.).
                                </li>
                                <li>Formularios (1 punto): al menos se deben incluir un formulario para registrar
                                    datos.
                                </li>
                                <li>Esquema CRUD (2 puntos): al menos una de las entidades debe tener un esquema CRUD
                                    completo: crear, leer, actualizar y borrar.
                                </li>
                                <li>Calidad de la implementación (3 puntos): se deben respetar las normas y consejos
                                    explicados
                                    durante los temas anteriores relativos a la calidad de la implementación.
                                </li>
                            </ul>
                        </div>
                        <div class="callout callout-info">
                            <h4>Extensión máxima</h4>
                            <p>Tendrás que presentar un documento Word donde informes del trabajo realizado. Este
                                informe debe contener dos partes: </p>
                            <ul>
                                <li>Manual de usuario: explicar el funcionamiento de la aplicación como si se tratara
                                    del manual facilitado a un cliente.
                                </li>
                                <li>Manual técnico: explicando las decisiones de diseño e implementación tomadas.</li>
                            </ul>
                            <p>Además del informe deberás incluir todo el código fuente de la aplicación
                                desarrollada.</p>
                            <p>Adicionalmente se valorará muy positivamente desplegar la aplicación web en un servidor
                                externo y facilitar una URL para su acceso.</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="callout callout-info">
                            <p>La aplicación que vamos a construir es un sistema de inventario simple para mostrar qué
                                álbumes
                                poseemos.
                                La página principal enumerará nuestra colección y nos permitirá agregar, editar y
                                eliminar
                                albumes.
                                Vamos a
                                necesitar cuatro páginas en nuestro sitio web:</p>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Pagina</th>
                                    <th>Descripción</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>Lista de albumes</td>
                                    <td>Esto mostrará la lista de álbumes y proporcionará enlaces para editarlos y
                                        eliminarlos.
                                        Además,
                                        se proporcionará un enlace para permitir agregar nuevos álbumes.
                                    </td>
                                </tr>
                                <tr>
                                    <td>Agregar nuevo album</td>
                                    <td>Esta página proporcionará un formulario para agregar un nuevo álbum.</td>
                                </tr>
                                <tr>
                                    <td>Editar album</td>
                                    <td>Esta página proporcionará un formulario para editar un álbum.</td>
                                </tr>
                                <tr>
                                    <td>Elimiar un album</td>
                                    <td>Esta página confirmará que queremos eliminar un álbum y luego eliminarlo.</td>
                                </tr>
                                </tbody>
                            </table>
                            <p>También necesitaremos almacenar nuestros datos en una base de datos. Solo necesitaremos
                                una tabla
                                con
                                estos campos:</p>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Nombre del campo</th>
                                    <th>Tipo</th>
                                    <th>¿Nulo?</th>
                                    <th>Notas</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>id</td>
                                    <td>integer</td>
                                    <td>no</td>
                                    <td>primary key, auto-increment</td>
                                </tr>
                                <tr>
                                    <td>artist</td>
                                    <td>varchar(255)</td>
                                    <td>No</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>title</td>
                                    <td>varchar(255)</td>
                                    <td>No</td>
                                    <td></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="callout callout-info">
                            <h4>Base de Datos</h4>
                            <a href="<?= $this->basePath('bd/bd.sql')?>" class="btn btn-primary text-white" style="text-decoration: none">Descargar</a>
                        </div>
                    </div>
                </div>
            </div>
            <!--            <div class="tab-pane fade" id="practica-2" role="tabpanel" aria-labelledby="practica-2-tab">...</div>-->
            <!--            <div class="tab-pane fade" id="practica-3" role="tabpanel" aria-labelledby="practica-3-tab">...</div>-->
        </div>
    </div>
</div>
