<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
<div class="row justify-content-center">
    <div class="col-md-3">
        <!-- Profile Image -->
        <div class="card card-primary card-outline">
            <div class="card-body box-profile">
                <div class="text-center">
                    <?php
                    $avatar = $this->gravatar('danielriveraayala@gmail.com');
                    echo $avatar->setAttributes(['class' => 'profile-user-img img-fluid img-circle'])->getImgTag();
                    ?>
                </div>

                <h3 class="profile-username text-center">Daniel Rivera</h3>

                <p class="text-muted text-center">Web Developer</p>


                <a href="https://github.com/danielriveraayala/" target="_blank"
                   class="btn btn-primary btn-block"><i class="fab fa-github-square"></i><b> Github</b></a>
                <a href="https://web.facebook.com/danielriveraayala.freelance" target="_blank"
                   class="btn btn-primary btn-block"><i class="fab fa-facebook-square"></i><b> Follow</b></a>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

        <!-- About Me Box -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Acerca de mi</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <strong><i class="fas fa-book mr-1"></i> Educación</strong>
                <p class="text-muted">
                <ul>
                    <li>Maestría en Dirección e Ingeniería de Sitios Web <small class="text-muted">(Actualmente
                            cursando)</small></li>
                    <li>Ing. Telematica</li>
                    <li>Lic. En Ciencias Computacionales y Comunicación</li>
                </ul>
                </p>
                <hr>
                <strong><i class="fas fa-map-marker-alt mr-1"></i> Ubicación</strong>
                <p class="text-muted">Morelia, Mich.</p>
                <hr>
                <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>
                <p class="text-muted">
                    <span class="tag tag-danger">UI Design</span>
                    <span class="tag tag-success">Coding</span>
                    <span class="tag tag-info">Javascript</span>
                    <span class="tag tag-warning">PHP</span>
                    <span class="tag tag-primary">Node.js</span>
                    <span class="tag tag-primary">PHP</span>
                    <span class="tag tag-primary">Zend Framework</span>
                    <span class="tag tag-primary">Laminas Framework</span>
                    <span class="tag tag-primary">CCS3</span>
                    <span class="tag tag-primary">Codeigniter</span>
                    <span class="tag tag-primary">Larabel</span>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="jumbotron">
            <h1 class="display-4">Bienvenido a <br>Ingenieria y Desarrollo en la Web</h1>
            <h3 class="text-muted">Implementación de una solución basada en una aplicación web</h3>
            <p>
                Esta es la primera practica para la materia de Ingenieria y Desarrollo en la Web, con fecha de entrega
                el 25 de mayo de 2020.
            </p>
            <hr class="my-4">
            <div class="callout callout-info">
                <h4>Descripción de la actividad y pautas de elaboración</h4>
                <p>Se debe diseñar y desarrollar una aplicación web funcional cumpliendo los criterios de evaluación
                    expuestos a continuación.</p>
            </div>
            <div class="callout callout-info">
                <h4>Criterios de evaluación</h4>
                <p>La aplicación a desarrollar puede tener una temática libre (por ejemplo: un blog, una página de
                    eventos, etc.) debe cumplir con los siguientes requisitos básicos:</p>
                <ul>
                    <li>La aplicación a desarrollar puede tener una temática libre (por ejemplo: un blog, una página de
                        eventos, etc.) debe cumplir con los siguientes requisitos básicos:
                    </li>
                    <li>Persistencia (2 puntos): se debe utilizar una base de datos MySQL o MongoDB (a elección del
                        alumno) para almacenar al menos dos tipos de entidades distintas que dependerán de la temática
                        de la aplicación (proyectos, tareas, partidos, jugadores, cuentas, etc.).
                    </li>
                    <li>Formularios (1 punto): al menos se deben incluir un formulario para registrar datos.</li>
                    <li>Formularios (1 punto): al menos se deben incluir un formulario para registrar datos.</li>
                    <li>Calidad de la implementación (3 puntos): se deben respetar las normas y consejos explicados
                        durante los temas anteriores relativos a la calidad de la implementación.
                    </li>
                </ul>
            </div>
            <div class="callout callout-info">
                <h4>Extensión máxima</h4>
                <p>Tendrás que presentar un documento Word donde informes del trabajo realizado. Este informe debe contener dos partes: </p>
                <ul>
                    <li>Manual de usuario: explicar el funcionamiento de la aplicación como si se tratara del manual facilitado a un cliente.</li>
                    <li>Manual técnico: explicando las decisiones de diseño e implementación tomadas.</li>
                </ul>
                <p>Además del informe deberás incluir todo el código fuente de la aplicación desarrollada.</p>
                <p>Adicionalmente se valorará muy positivamente desplegar la aplicación web en un servidor externo y facilitar una URL para su acceso.</p>
            </div>
        </div>
    </div>
</div>