<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
<div class="row justify-content-center">
    <div class="col-md-3">
        <!-- Profile Image -->
        <div class="card card-primary card-outline">
            <div class="card-body box-profile">
                <div class="text-center">
                    <?php
                    $avatar = $this->gravatar('danielriveraayala@gmail.com');
                    echo $avatar->setAttributes(['class' => 'profile-user-img img-fluid img-circle'])->getImgTag();
                    ?>
                </div>

                <h3 class="profile-username text-center">Daniel Rivera</h3>

                <p class="text-muted text-center">Web Developer</p>

                <a href="https://github.com/danielriveraayala/ingenieria-y-desarrollo-en-la-web-unir" target="_blank"
                   class="btn btn-primary btn-block"><i class="fab fa-github-square"></i><b> Codigo fuente</b></a>
                <a href="https://github.com/danielriveraayala/" target="_blank"
                   class="btn btn-primary btn-block"><i class="fab fa-github-square"></i><b> Mi Github</b></a>
                <a href="https://web.facebook.com/danielriveraayala.freelance" target="_blank"
                   class="btn btn-primary btn-block"><i class="fab fa-facebook-square"></i><b> Follow</b></a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="jumbotron">
            <h1 class="display-4">Bienvenido a Ingenieria y Desarrollo en la Web</h1>
            <h3 class="text-muted">Repositorio de practicas</h3>
            <p>
                Este es el repositorio base para la realizacion de las practicas solicitadas en la materia
            </p>
            <p>Las practicas se encuentran en el modulo Dashboard</p>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-md-9">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Acerca de mi</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <strong><i class="fas fa-book mr-1"></i> Educación</strong>
                <p class="text-muted">
                <ul>
                    <li>Maestría en Dirección e Ingeniería de Sitios Web <small class="text-muted">(Actualmente
                            cursando)</small></li>
                    <li>Ing. Telematica</li>
                    <li>Lic. En Ciencias Computacionales y Comunicación</li>
                </ul>
                </p>
                <hr>
                <strong><i class="fas fa-map-marker-alt mr-1"></i> Ubicación</strong>
                <p class="text-muted">Morelia, Mich.</p>
                <hr>
                <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>
                <p class="text-muted">
                    <span class="tag tag-danger">UI Design</span>
                    <span class="tag tag-success">Coding</span>
                    <span class="tag tag-info">Javascript</span>
                    <span class="tag tag-warning">PHP</span>
                    <span class="tag tag-primary">Node.js</span>
                    <span class="tag tag-primary">PHP</span>
                    <span class="tag tag-primary">Zend Framework</span>
                    <span class="tag tag-primary">Laminas Framework</span>
                    <span class="tag tag-primary">CCS3</span>
                    <span class="tag tag-primary">Codeigniter</span>
                    <span class="tag tag-primary">Larabel</span>
                </p>
            </div>
        </div>
    </div>
</div>